version: '3.8'

services:
  # Our Iris API service
  iris-api:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: iris-api-compose
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      # The API needs to find the MLflow server on the host machine
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
    # This ensures the container can connect back to the host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # The Prometheus monitoring service
  prometheus:
    image: prom/prometheus:v2.45.0 # Use an official Prometheus image
    container_name: prometheus-compose
    ports:
      - "9090:9090" # Map host port 9090 to Prometheus's port
    # Mount our prometheus.yml config file into the container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
