version: '3.8'

services:
  # Our Iris API service
  iris-api:
    build: .
    container_name: iris-api-compose
    ports:
      - "8000:8000"
    environment:
      # The API now connects to the 'mlflow' container on port 5000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    # This makes the mlflow service available to the api service
    depends_on:
      - mlflow

  # The Prometheus monitoring service
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus-compose
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # This makes the api service available to the prometheus service
    depends_on:
      - iris-api

  # The MLflow Tracking Server service
  mlflow:
    image: python:3.9-slim # Use a simple python image
    container_name: mlflow-compose
    ports:
      - "5000:5000"
    # Use a volume to persist the MLflow data outside the container
    volumes:
      - mlflow_data:/mlflow
    working_dir: /mlflow
    command: >
      bash -c "pip install mlflow boto3 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts"

volumes:
  mlflow_data:
